name: Run Keploy API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Keploy CLI
      run: |
        curl --silent -L https://keploy.io/ent/install.sh | bash

    - name: Run Keploy Test Suite
      run: |
        export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
        keploy test-suite --app=<your_app_id_from_keploy_dashboard> --base-path=http://localhost:8080/api/notes --cloud
